version: "3"
services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.production
    image: ghcr.io/lamkimphu258/thich-hoc:latest
    container_name: thich-hoc-app
    environment:
      APP_NAME: "my production"
    ports:
      - "${APP_PORT:-8001}:80"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "http://127.0.0.1:${APP_PORT:-8000}/fpm-ping",
        ]
      retries: 3
      timeout: 10s
    volumes:
      - ".env:/var/www/html/.env"
