version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: thich-hoc/app
    container_name: thich-hoc-app
    environment:
      APP_NAME: "my production"
    ports:
      - "${APP_PORT:-8000}:80"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "http://127.0.0.1:${APP_PORT:-8000}/fpm-ping",
        ]
      retries: 3
      timeout: 10s
